### ISSUE TITLE
How do I setup the directory for org-mobile-push?

### ISSUE THREAD

**Issue by drozzy** [matburt/mobileorg-android#442]
The doc says:

    Set up the location of your org-files by configuring and running ‘org-mobile-push’ in emacs.

Can anyone explain it in more detail. How do I "configure" it?

**Comment by wxl** [comment]
@drozzy in case you haven't figured this out, it's meant to be done on a machine that has access to the files and that has emacs on it. generally, this is your PC.

**Comment by drozzy** [comment]
No sure what PC has to do with my phone... Anyways, I've kind-of abandoned this, so if someone has similar questions, I think they should open another issue with their questions.

**Comment by brianhlin** [comment]
MobileOrg is essentially just a client that talks to your Emacs server that has your org files.

**Comment by drozzy** [comment]
@binarin Oh, would be nice if this sentence was in the docs. Preferably first.
