### ISSUE TITLE
Sync via Syncthing

### ISSUE THREAD

**Issue by csantosb** [matburt/mobileorg-android#449]
Have anyone tried sync via open source syncthing ? I am having an issue with empty files, mobileorg is lost ... This is probably related to syncthing, but still, any workaround ?

**Comment by brianhlin** [comment]
I've got my setup mostly working via Syncthing. What exactly are you having issues with?

**Comment by csantosb** [comment]
Well, no more issues now. Just gave up trying and moved to orgzly + syncthing.
