### ISSUE TITLE
Feature Request: Sync through git (i.e. sparkleshare)

### ISSUE THREAD

**Issue by zakkak** [matburt/mobileorg-android#465]
I would like to request a syncing mechanism supporting `git`, much like how sparkleshare works.

How hard would the implementation of that feature be?  
Could the ssh/scp code-base be used?

I believe executing `git pull` followed by a `git commit -a -m "some message"` every N minutes would be enough as a starting point.

Is there a way to introduce some dependency on the `git` command?  Or even better are there any android-libraries that could be used?

I am willing to develop that feature but since I am not familiar with android-development I would need some help.

**Comment by zakkak** [comment]
A related patch can be found at https://github.com/bssb/mobileorg-android/commit/4afee2eb91a14e291db25319ef7fe37b56118764

**Comment by erikmd** [comment]
Also, did you take a look at the similar project https://github.com/hdweiss/mOrgAnd ? It is still a pre-release, but AFAIK it has been specifically designed to support `git` synchronization of `org-mode` files.

**Comment by zakkak** [comment]
No, I am not aware of it. Thanks for the reference!
