### ISSUE TITLE
New mobileorg:  Add node will failed when no user org file

### ISSUE THREAD

**Issue by tumashu** [matburt/mobileorg-android#481]
If have no user org file, add a node in TODO will do nothing, maybe let user create a new org file when init save node?

**Comment by wizmer** [comment]
I was not aware of this crash. About your suggestion, I'll think about it but it is not so simple. There are good chances the user wants to create a node in an already file.

**Comment by tumashu** [comment]
a simple solution is that show "Add a org file" instead of "add a node" when no org file

**Comment by tumashu** [comment]
or just do not show "add node" in TODO and Agenda

**Comment by wizmer** [comment]
Yeah I think I am just going to show a message like:

"This is the list of all your TODO items"
"It is currently empty"

**Comment by tumashu** [comment]
goog idea
