### ISSUE TITLE
Signing in ... waiting waiting waiting 

### ISSUE THREAD

**Issue by otesuji** [matburt/mobileorg-android#486]
I did everything right. SSh key pair created correctly. Pub key on Github (the right way), selected the right private key on MobileOrg. Add .git to my absolute path  etc...
Click on Done. "Signing in ..." I'v been waiting for 10 minutes now and nothing change.
I didn't had nay authentification failure etc...

**Comment by otesuji** [comment]
oups.... suddenly its stop and ... its is working so far. Good job.

**Comment by wizmer** [comment]
Did you add a lot of files in your repository ?
Maybe I should a progress bar ?

**Comment by otesuji** [comment]
yes exactly. I have plenty of big org files on my directory. No problem on my Dell though. a progress bar would be perfect.
