### ISSUE TITLE
Lack of support for relative paths breaks Gitolite3 interop

### ISSUE THREAD

**Issue by khaije1** [matburt/mobileorg-android#487]
@wizmer it seems mobileorg's expectation of an absolute path doesn't play well with gitolite's automatic path munging, (gitolite3@example.org:orgnotes.git). In any event I was unable to get it working. 

Any advice or light at the end of the tunnel in this use case? 
Does mobileorg-android needs shell access in addition to exchanging git information?

FYI as a long-shot, I also tried adding ':orgnotes' in the Absolute Path field which resulted in the same .

ref: http://gitolite.com/gitolite/index.html

**Comment by wizmer** [comment]
I don't know gitolite but from the URL you've put the correct configuration should be:

username: gitolite3
Absolute path: orgnotes.git
Host: example.org

If this does not work come back to me and I'll investigate more.

**Comment by khaije1** [comment]
Gitolite operates by restricting the shell access that's granted to SSH connections, allowing only git commands. Is that problematic for the way that mobileorg works?


This is the error message in the logs:
```
Sep 11 21:38:48 <xx-redacted-xx> sshd[3687]: error: Received disconnect from <xx-redacted-xx>: 3: com.jcraft.jsch.JSchException: Auth fail [preauth]                                              
``` 

Here are the configs I'm using:
method: sshkey (passwordless)
user: gitolite3
ssh_priv: <xx-path-to-file-xx>
path: <xx-path-to--xx>
host: <xx-redacted-xx>
port: 22

**Comment by khaije1** [comment]
How can I assist with troubleshooting?

**Comment by khaije1** [comment]
Update: testing with latest release the belt clarified error message indicates"unable to access private key". Tried both "Android" and "File" way. The file was transferred over to phone via Google drive client.

**Comment by wizmer** [comment]
Have you checked if the file you passed had the correct permissions ?

**Comment by khaije1** [comment]
Yes but the error is unchanged. I'm using the EStrong File Browser to check the sshkey's file permissions and its says its rw-rw-. 

I'm eager to use the app but realize this issue may be unrelated to the app itself so I'll close the issue. If you have any suggestions I'll be interested to know but it shouldn't count as an open issue against the project.

Cheers!
